Traceback (most recent call last):
  File "/home/iterahero2023/iterahero2023/main.py", line 492, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/iterahero2023/iterahero2023/main.py", line 381, in main
    async with client:
  File "/home/iterahero2023/.local/lib/python3.9/site-packages/aiomqtt/client.py", line 1088, in __aenter__
    raise MqttError(str(error)) from None
aiomqtt.error.MqttError: [Errno -3] Temporary failure in name resolution
